"""
PHASE 3 — AI TEST GENERATOR
Reads your app source code and uses Claude to write edge-case tests
that humans typically miss.
Run: python scripts/ai_test_generator.py
"""
import os
import sys
import json
import textwrap
from pathlib import Path

APP_PATH = os.path.join(os.path.dirname(__file__), "../app/main.py")
OUT_PATH  = os.path.join(os.path.dirname(__file__), "../tests/unit/test_ai_generated.py")


def read_source(path: str) -> str:
    with open(path) as f:
        return f.read()


def call_claude(source_code: str) -> str:
    """Call Claude API to generate edge-case tests for the given source."""
    try:
        import urllib.request, json as _json
        payload = {
            "model": "claude-sonnet-4-20250514",
            "max_tokens": 1000,
            "messages": [{
                "role": "user",
                "content": f"""You are a senior QA engineer. Read this Flask REST API code and write pytest tests that cover edge cases a human would typically miss.

Rules:
- Use pytest fixtures: client, auth_headers, registered_user (already defined in conftest.py)
- Focus on: boundary values, null inputs, unicode, very long strings, concurrent-like patterns
- Each test must have a clear docstring explaining what bug it catches
- Return ONLY valid Python code, no explanation, no markdown fences

Source code:
{source_code[:3000]}
"""
            }]
        }
        req = urllib.request.Request(
            "https://api.anthropic.com/v1/messages",
            data=_json.dumps(payload).encode(),
            headers={"Content-Type": "application/json"},
            method="POST"
        )
        with urllib.request.urlopen(req, timeout=30) as resp:
            data = _json.loads(resp.read())
            return data["content"][0]["text"]
    except Exception as e:
        return f"# AI generation failed: {e}\n# Run manually with an Anthropic API key set."


def generate():
    print("Reading source code...")
    source = read_source(APP_PATH)

    print("Calling Claude to generate edge-case tests...")
    generated = call_claude(source)

    header = textwrap.dedent(f'''\
        """
        AI-GENERATED TESTS — Phase 3 SmartTestKit
        Auto-generated by Claude. Review before committing.
        Generated from: app/main.py
        """
        import pytest

    ''')

    with open(OUT_PATH, "w", encoding="utf-8") as f:
        f.write(header + generated)

    print(f"✓ Tests written to: {OUT_PATH}")
    print("  Review the file, then run: pytest tests/unit/test_ai_generated.py -v")


if __name__ == "__main__":
    generate()
